### ISSUE TITLE
Don't work for me

### ISSUE THREAD

**Issue by samuelemeo** [davidteren/lpx_links#1]
MacBook-Pro-di-Samuele:Downloads samuele$ cd ~/Downloads; mkdir -p lpx_links/app ; cd lpx_links/app ; curl -#L https://github.com/davidteren/lpx_links/tarball/master | tar -xzv --strip-components 1 ; ./lpx_links.rb
######################################################################## 100,0%
x README.md
x lib/
x lib/config.rb
x lpx_links.rb
./lpx_links.rb:29:in `block in json_parse': undefined method `<<' for nil:NilClass (NoMethodError)
	from ./lpx_links.rb:28:in `each'
	from ./lpx_links.rb:28:in `json_parse'
	from ./lpx_links.rb:12:in `launch'
	from ./lpx_links.rb:62:in `<main>'
MacBook-Pro-di-Samuele:app samuele$ clear

**Comment by davidteren** [comment]
Do you have Logic Pro X 10.2.0 installed?
What version of OS X are you running?

**Comment by samuelemeo** [comment]
Yes, Logic Pro X 10.2.0 and OS X 10.11

**Comment by davidteren** [comment]
It should work with OS X 10.11 now.

**Comment by samuelemeo** [comment]
Yes, it works now.
Thanks

**Comment by davidteren** [comment]
Great.
